### ISSUE TITLE
Should remove extra directories

### ISSUE THREAD

**Issue by alexandru-calinoiu** [AlexandraDamaschin/blog#1]
There a couple of folders that don't belong to the project

You can see the ruby ignored files here https://www.gitignore.io/api/ruby
And for rubymine https://www.gitignore.io/api/jetbrains

**Comment by AlexandraDamaschin** [comment]
Updated .gitignore & clean directories with:
git rm  -r --cached .

Not sure if that's good, but the node_modules folder it's still there so it seems to me something didn't clean up well.
